version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sp_network
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - sp_network

volumes:
  pgdata:

networks:
  sp_network:
    driver: bridge
    name: sp_network
